accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"  # required when using namespace in URLS

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/', views.profile, name='profile'),
    path('profile/change_password', views.change_password, name='change_password'),
]

project_7/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', views.home, name='home'),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/models.py
"""Account Models"""
from django.db import models
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    """Get the user directory path"""
    # file will be uploaded to MEDIA_ROOT/avatars/user/<filename>
    return 'avatars/{0}/{1}'.format(instance.user, filename)


class Profile(models.Model):
    """Define the Profile Model (linked to the User Model)."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField()  # Required field
    bio = models.TextField(help_text='Minimum 10 characters')  # Required field
    avatar = models.ImageField(
        upload_to=user_directory_path,
        max_length=255,
        null=True,
        blank=True,
        default='placeholder/default.png',
    )  # Optional field
    city = models.CharField(max_length=100)  # Required field
    county = models.CharField(max_length=255, blank=True)  # Optional field
    country = models.CharField(max_length=100)  # Required field
    interests = models.TextField(blank=True)  # Optional field
    website = models.URLField(blank=True,)  # Optional field

accounts/forms.py
"""Accounts Forms."""

from django import forms
from PIL import Image

from . import models
from . import validators

from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.db.models import TextField
from django.forms import DateField
from django_summernote.widgets import SummernoteInplaceWidget


# ---Signup form
class SignUpForm(UserCreationForm):
    """Define the SignUpForm which extends UserCreationForm"""
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    verify_email = forms.EmailField(
        required=True,
        label="Confirm email:",
        help_text='Enter the same email as before, for verification.'
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'verify_email',
            'password1',
            'password2',
        )

    def clean(self):
        """Validate that the emails match"""
        cleaned_data = super().clean()
        validators.EmailMatchValidator().validate(cleaned_data['email'], cleaned_data['verify_email'])
        return cleaned_data
# ---/Signup form


# ---Edit User form
class EditUserForm(forms.ModelForm):
    """Define the Edit User Form."""
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
        )
# ---/Edit User form


# ---Edit Email form
class EditEmailForm(forms.ModelForm):
    """Define the Edit User Form."""
    email = forms.EmailField(
        required=True,
        label="Enter your new email address:")
    verify_email = forms.EmailField(
        required=True,
        label="Confirm email:",
        help_text='Enter the same email as before, for verification.'
     )

    class Meta:
        model = User
        fields = (
            'email',
            'verify_email',
        )

    def clean(self):
        """Validate that the emails match"""
        cleaned_data = super().clean()
        validators.EmailMatchValidator().validate(cleaned_data['email'], cleaned_data['verify_email'])
        return cleaned_data
# ---/Edit User form


# ---Profile form
class ProfileForm(forms.ModelForm):
    """Define the Profile Form."""

    def clean_bio(self):
        """Validate the bio field"""
        bio = self.cleaned_data['bio']
        if len(bio) < 10:
            raise ValidationError('Biography must contain at least 10 characters.')
        return bio

    date_of_birth = DateField(
        error_messages={'invalid': 'Date should be in one of the following formats: '
                                   'YYYY-MM-DD or MM/DD/YYY or MM/DD/YY'},
        label="Date of birth",
    )

    bio = TextField(validators=[clean_bio])

    class Meta:
        model = models.Profile

        fields = (
            'date_of_birth',
            'city',
            'county',
            'country',
            'bio',
            'interests',
            'website',
        )
        widgets = {
            'bio': SummernoteInplaceWidget(),
            'interests': SummernoteInplaceWidget(),
        }
        labels = {
            'bio': 'Biography',
            'county': 'State / County (optional)',
            'interests': "Interests (optional)",
            'website': "Website (optional)",
        }
# ---/Profile form


# ---Avatar form
class AvatarForm(forms.ModelForm):
    """Define the Avatar Form."""
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    rotate = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = models.Profile
        fields = ('avatar', 'x', 'y', 'width', 'height', 'rotate')
        labels = {'avatar': '', }
        widgets = {
            'avatar': forms.FileInput(attrs={
                'accept': 'image/*'
            })
        }

    def save(self):
        photo = super(AvatarForm, self).save()
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        r = self.cleaned_data.get('rotate')

        r = -r  # swap negative to positive and vise versa

        image = Image.open(photo.avatar)
        rotated_image = image.rotate(r, expand=True)
        cropped_image = rotated_image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize((400, 400), Image.ANTIALIAS)
        resized_image.save(photo.avatar.path)

        return photo
# # ---/Avatar form


# ---Change Password form
class ChangePasswordForm(forms.Form):
    """Define the Edit User Form."""

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        self.fields["current_password"].validators.append(validators.CurrentPasswordValidator(user))
        self.fields["new_password"].validators.append(validators.ChangedValidator(user))
        self.fields["new_password"].validators.append(validators.SimilarValidator(user))

    current_password = forms.CharField(widget=forms.PasswordInput, required=True)
    new_password = forms.CharField(widget=forms.PasswordInput, required=True, validators=[
        validate_password,
        validators.MixcaseValidator,
        validators.NumberValidator,
        validators.SpecialCharacterValidator,
    ])
    confirm_password = forms.CharField(widget=forms.PasswordInput, required=True,
                                       label="Confirm new password",)

    def clean(self):
        """Validate that the emails match"""
        cleaned_data = super().clean()
        validators.PasswordMatchValidator().validate(self.data['new_password'], cleaned_data['confirm_password'])
        return cleaned_data
# ---/Change Password form

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render

from . import forms
from . import models


def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(
                        reverse('accounts:profile')
                    )
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    form = forms.SignUpForm()
    if request.method == 'POST':
        form = forms.SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            messages.success(
                request,
                "Account setup successfully! You've been signed in too."
            )
            return HttpResponseRedirect(reverse('accounts:create_profile'))

    return render(request, 'accounts/sign_up.html', {
        'form': form,
    })


@login_required
def create_profile(request):
    """Populate the Profile after the user has been created."""
    profile_form = forms.ProfileForm()
    user = request.user
    if request.method == 'POST':
        try:
            user.profile = request.user.profile  # Set Profile instance for the current user
        except models.Profile.DoesNotExist:
            user.profile = models.Profile(user=request.user)  # Set the Profile instance for new user

        profile_form = forms.ProfileForm(data=request.POST, instance=user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(
                request,
                "Profile saved successfully."
            )
            return HttpResponseRedirect(reverse('accounts:profile'))

    return render(request, 'accounts/create_profile.html', {
        'profile_form': profile_form,
    })


def sign_out(request):
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


@login_required
def edit_profile(request):
    """Define the Edit Profile view"""
    user = request.user
    form = forms.EditUserForm(instance=user)
    email_form = forms.EditEmailForm(instance=user)
    avatar_form = forms.AvatarForm()
    try:
        user.profile = request.user.profile  # Set Profile instance for the current user
    except models.Profile.DoesNotExist:
        user.profile = models.Profile(user=request.user)  # Set the Profile instance for new user

    profile_form = forms.ProfileForm(instance=user.profile)
    if request.method == 'POST':
        if 'rotate' in request.POST:
            avatar_form = forms.AvatarForm(instance=user.profile, data=request.POST, files=request.FILES)
            if avatar_form.is_valid():
                avatar_form.save()
                messages.success(request, "Avatar image updated successfully.")
                return HttpResponseRedirect(reverse('accounts:profile'))

        elif 'update_name' in request.POST:
            form = forms.EditUserForm(data=request.POST, instance=user)
            profile_form = forms.ProfileForm(data=request.POST, instance=user.profile)
            if form.is_valid() and profile_form.is_valid():
                form.save()
                profile_form.save()
                messages.success(request, "Profile updated successfully.")
                return HttpResponseRedirect(reverse('accounts:profile'))

        elif 'update_email' in request.POST:
            email_form = forms.EditEmailForm(data=request.POST, instance=user)
            if email_form.is_valid():
                email_form.save()
                messages.success(request, "Email updated successfully.")
                return HttpResponseRedirect(reverse('accounts:profile'))
            else:
                return render(request, 'accounts/edit_profile.html', {
                    'current_user': user,
                    'form': form,
                    'email_form': email_form,
                    'collapse': 'false',  # Keep the email panel open to show errors
                })

    return render(request, 'accounts/edit_profile.html', {
        'current_user': user,
        'form': form,
        'email_form': email_form,
        'profile_form':  profile_form,
        'avatar_form': avatar_form,
    })


@login_required
def change_password(request):
    """Define the change password view."""
    user = request.user
    change_password_form = forms.ChangePasswordForm(request.user)
    if request.method == 'POST':
        change_password_form = forms.ChangePasswordForm(request.user, data=request.POST)
        if change_password_form.is_valid():
            user.set_password(change_password_form.cleaned_data['new_password'])
            user.save()
            update_session_auth_hash(request, user)  # sign the user back in
            messages.success(request, "Password updated successfully.")
            return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, 'accounts/change_password.html', {
        'current_user': user,
        'change_password_form': change_password_form,
    })


@login_required
def profile(request):
    """Define the Profile view"""
    user = request.user
    try:
        user.profile = request.user.profile  # Set Profile instance for the current user
    except models.Profile.DoesNotExist:
        user.profile = models.Profile(user=request.user)  # Set the Profile instance for new user
    avatar_form = forms.AvatarForm()
    if request.method == 'POST':
        avatar_form = forms.AvatarForm(instance=user.profile, data=request.POST, files=request.FILES)
        if avatar_form.is_valid():
            avatar_form.save()
            messages.success(request, "Avatar image updated successfully.")
            return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, 'accounts/profile.html', {
        'current_user': request.user,
        'avatar_form': avatar_form,
    })

accounts/templates/accounts/change_password.html
{% extends "layout.html" %}
{% load static %}
{% load widget_tweaks %}
{% load accounts_extras %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/password.min.css" %}">
{% endblock %}
{% block title %}Change password | {{ current_user.first_name }} {{ current_user.last_name }}{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="display-3 mb-5">Change Password</h1>
        <p>User: {{ current_user.first_name }} {{ current_user.last_name }}</p>
        {# change password form #}
        <form method="POST" action="{% url 'accounts:change_password' %}">
            {% csrf_token %}
            {% for hidden_field in change_password_form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}

            <input type="hidden" id="name-check" name="name-check"
                   value="{{ current_user.first_name }}{{ current_user.last_name }}{{ current_user.username }}">

            {% if change_password_form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {% for error in change_password_form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}

            {% for field in change_password_form.visible_fields %}
                <div class="form-group">
                    {{ field.label_tag }}

                    {% if change_password_form.is_bound %}

                        {% if field.errors %}
                            {% render_field field class="form-control is-invalid" %}
                            {% for error in field.errors %}
                                <div class="invalid-feedback">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% else %}
                            {% render_field field class="form-control is-valid" %}
                        {% endif %}
                    {% else %}
                        {% render_field field class="form-control" %}
                    {% endif %}


                    {% if field.help_text %}
                        <small class="hint">{{ field.help_text|add_help_style|safe }}</small>
                    {% endif %}
                </div>
            {% endfor %}
            <input type="submit" class="button-primary mt-4" value="Update password">
        </form>
        {# /change password form #}
    </div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends "layout.html" %}
{% load static %}
{% load widget_tweaks %}
{% load accounts_extras %}
{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
          integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static "css/bs-4/summernote-bs4.min.css" %}">
    <link rel="stylesheet" href="{% static "css/cropper.min.css" %}">
{% endblock %}
{% block title %} Edit profile | {{ current_user.first_name }} {{ current_user.last_name }}{% endblock %}
{% block body %}
    <div class="container">
        <h1 class="display-3 mb-2">Edit Your Profile</h1>
        <img class="img-thumbnail mt-4" src="{{ current_user.profile.avatar.url }}" width="200px"
             alt="{{ current_user.first_name }} {{ current_user.last_name }}">
        <form method="post" enctype="multipart/form-data" id="formUpload">
            {% csrf_token %}
            {{ avatar_form.non_field_errors }}
            {% for hidden_field in avatar_form.hidden_fields %}
                {{ hidden_field.errors }}
                {{ hidden_field }}
            {% endfor %}
            <div class="button button-primary btn-sm px-4 py-2 mt-2 e-button sudo_btn">
                <span>Change</span>
                <input id="id_avatar" type="file" name="avatar" accept="image/*" class="upload">
            </div>
        </form>
        {% include "accounts/image_editor_modal.html" %}
        <hr>
        <h4 class="mt-4 mb-4">{{ current_user.first_name }} {{ current_user.last_name }}</h4>
        <p class="mt-3 mb-4">Username: <span class="text-light-green">{{ current_user.username }}</span></p>
        <p class="mt-3 mb-4">Password: <span class="text-light-green">
            &#x2022;&#x2022;&#x2022;&#x2022;&#x2022;&#x2022;&#x2022;&#x2022;</span>
            <a class="button button-primary py-1 e-button sudo_btn"
               href="{% url 'accounts:change_password' %}" role="button">Change</a></p>
        <p class="mt-3 mb-4">Email: {{ current_user.email }}
            <button type="button" data-toggle="collapse" data-target="#collapseExample"
                    aria-expanded="false" aria-controls="collapseExample"
                    class="button-primary btn-sm px-4 py-2 align-top e-button">Change
            </button>
        </p>
    </div>

    {# edit email form #}
    <div class="{% show_panel collapse %}  mb-5" id="collapseExample">
        <div class="card card-body bg-light pb-0">
            <form method="POST" action="{% url 'accounts:edit_profile' %}">
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}

                {% if email_form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in email_form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}

                {% for field in email_form.visible_fields %}
                    <div class="form-group">
                        {{ field.label_tag }}

                        {% if email_form.is_bound %}

                            {% if field.errors %}
                                {% render_field field class="form-control is-invalid" %}
                                {% for error in field.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% else %}
                                {% render_field field class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field field class="form-control" %}
                        {% endif %}

                        {% if field.help_text %}
                            <small class="hint">{{ field.help_text|add_help_style|safe }}</small>
                        {% endif %}
                    </div>
                {% endfor %}
                <input type="submit" name="update_email" class="button-primary btn-sm px-4 py-3 e-button mb-1"
                       value="Update email">
            </form>
        </div>
    </div>
    {# /edit email form #}
        <hr>

    {# user form #}
    <div class="container ninety">
    <form method="POST" action="{% url 'accounts:edit_profile' %}">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}

                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field value=field.value class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                    <small class="hint">{{ field.help_text|add_help_style|safe }}</small>
                {% endif %}
            </div>
        {% endfor %}
        {# /user form #}

        {# profile form #}
        {% for hidden_field in profile_form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% if profile_form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in profile_form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}

        {% for field in profile_form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}

                {% if profile_form.is_bound %}

                    {% if field.errors %}
                        {% if field.name != 'bio' and field.name != 'interests' %}
                            {% render_field field class="form-control is-invalid" %}
                        {% else %}
                            {% render_field field value=field.error class="clean-button wsiwyg-is-invalid" %}
                        {% endif %}
                        {% for error in field.errors %}
                            {% if field.name != 'bio' and field.name != 'interests' %}
                                <div class="invalid-feedback">
                                    {{ error }}
                                </div>
                            {% else %}
                                <div class="wsiwyg-invalid-message">
                                    {{ error }}
                                </div>
                            {% endif %}

                        {% endfor %}
                    {% else %}
                        {% if field.name != 'bio' and field.name != 'interests' %}
                            {% render_field field value=field.value class="form-control is-valid" %}
                        {% else %}
                            {% render_field field value=field.value class="clean-button wsiwyg-is-valid" %}
                        {% endif %}
                    {% endif %}
                {% else %}
                    {% if field.name != 'bio' and field.name != 'interests' %}
                        {% render_field field value=field.value class="form-control" %}
                    {% else %}
                        {% render_field field value=field.value class="clean-button" %}
                    {% endif %}
                {% endif %}

                {% if field.help_text %}
                    <small class="hint">{{ field.help_text|add_help_style|safe }}</small>
                {% endif %}
            </div>
        {% endfor %}
        <input type="submit" name="update_name" class="button-primary mt-4" value="Save">
    </form>
    {# /profile form #}
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'layout.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/cropper.min.css" %}">{% endblock %}
{% block title %}View profile | {{ current_user.first_name }} {{ current_user.last_name }}{% endblock %}
{% block body %}
    <div class="container seventy">
        <h1 class="display-3 mb-2">{{ current_user.first_name }} {{ current_user.last_name }}</h1>
        {% if not current_user.profile.avatar.url %}
            <img class="img-thumbnail mt-4" src="/media/placeholder/default.png" width="200px"
                 alt="Default Avatar">
        {% endif %}
        <img class="img-thumbnail mt-4" src="{{ current_user.profile.avatar.url }}" width="200px"
             alt="{{ current_user.first_name }} {{ current_user.last_name }}">
        <form method="post" enctype="multipart/form-data" id="formUpload">
            {% csrf_token %}
            {{ avatar_form.non_field_errors }}
            {% for hidden_field in avatar_form.hidden_fields %}
                {{ hidden_field.errors }}
                {{ hidden_field }}
            {% endfor %}
            <div class="button button-primary btn-sm px-4 py-2 mt-2 e-button sudo_btn">
                <span>Change</span>
                <input id="id_avatar" type="file" name="avatar" accept="image/*" class="upload">
            </div>
        </form>
        {% include "accounts/image_editor_modal.html" %}
        <hr class="mt-2">
        <h4 class="mt-5 mb-2">Username</h4>
        <p><span class="text-light-green">{{ current_user.username }}</span></p>
        <h4 class="mt-5 mb-2">Email</h4>
        <p>{{ current_user.email|urlize }}</p>
        {% if current_user.profile.city %}
            <h4 class="mt-5 mb-2">City</h4>
            <p>{{ current_user.profile.city }}</p>
        {% endif %}
        {% if current_user.profile.county %}
            <h4 class="mt-5 mb-2">State / County</h4> <p>{{ current_user.profile.county }}</p>
        {% endif %}
        {% if current_user.profile.country %}
            <h4 class="mt-5 mb-2">Country</h4>
            <p>{{ current_user.profile.country }}</p>
        {% endif %}
        {% if current_user.profile.date_of_birth %}
            <h4 class="mt-5 mb-2">Date of birth</h4>
            <p>{{ current_user.profile.date_of_birth }}</p>
        {% endif %}
        {% if current_user.profile.bio %}
            <hr>
            <h4 class="mt-5 mb-2">Bio</h4>
            <p>{{ current_user.profile.bio|safe }}</p>
            <hr>
        {% endif %}
        {% if current_user.profile.interests and current_user.profile.interests != '<br>' %}
            <h4 class="mt-5 mb-2">Interests</h4>
            <p>{{ current_user.profile.interests|safe }}</p>
            <hr>
        {% endif %}
        {% if current_user.profile.website %}
            <h4 class="mt-5 mb-2">Website</h4>
            <p>{{ current_user.profile.website|urlize }}</p>
        {% endif %}
        <h4 class="mt-5 mb-2">Date joined</h4>
        <p>{{ current_user.date_joined }}</p>
        <p class="mt-4 mb-0"><a class="button button-primary btn-sm px-4 py-2 e-button sudo_btn"
                                href="{% url 'accounts:edit_profile' %}" role="button">Edit profile</a></p>
    </div>
{% endblock %}