accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"  # required when using namespace in URLS

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/', views.profile, name='profile'),
    path('profile/change_password', views.change_password, name='change_password'),
]

project_7/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', views.home, name='home'),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/home.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
    <div class="grid-25">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="#">Plan your visit</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Get involved</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Events</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Shop</a>
            </li>

        </ul>
    </div>
    <div class="grid-75">
        <h1 class="display-3 mb-3">Welcome to Circle<sup>&#8482;</sup> </h1>
        <img src="{% static 'images/District_3094b.jpg' %}" class="img-fluid" alt="Chiswick Park Tube Station">
        <figcaption class="figure-caption mt-2">Chiswick Park Tube Station. Image &#169; Chris Guy 2009</figcaption>
        <h2 class="display-3 mt-5">A view of Chiswick Park</h2>
        <p>Chiswick park tube station was designed by Charles Holden in a modern European style using brick, reinforced
            concrete and glass. Holden's design was inspired by Alfred Grenander's underground station Krumme Lanke
            in Berlin.
            <p>Similar to the station at Arnos Grove that Holden designed for the eastern Piccadilly line extension,
            Chiswick Park station features a tall semi-circular ticket hall adjacent to the embankment carrying the
            tracks. Externally the brick walls of the ticket hall are punctuated with panels of clerestory windows
            and the structure is capped with a flat concrete slab roof which abuts the cantilevered concrete canopy
            of the westbound platform. A similar canopy shelters the eastbound platform accessed through the embankment.
            <p>To make the station's location visible from Chiswick High Road the station was also provided with a square
        brick tower surmounted by the UNDERGROUND roundel and the station's name.</p>
            <p>The station has been a Grade II listed building since 18 February 1987.</p>
            <p>For more information, please see the <a href="https://en.wikipedia.org/wiki/Chiswick_Park_tube_station"
                                                       target="_blank">Chiswick Park Wikipedia page</a>.</p>
    </div>
{% endblock %}

templates/layout.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- Font Awesome Icons
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script src="https://kit.fontawesome.com/bd0f673c70.js" crossorigin="anonymous"></script>
    <!-- jQuery
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
{#    <script type="text/javascript" src="{% static "js/jquery-3.1.1.min.js" %}"></script>#}
    <script type="text/javascript" src="{% static "js/jquery-3.5.0.min.js" %}"></script>

    <!-- Bootstrap CSS & JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/bs-4/bootstrap.min.css" %}">
    <script type="text/javascript" src="{% static "js/bs-4/bootstrap.bundle.min.js" %}"></script>

    <!-- JavaScript
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript" src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>


    <!-- Datepicker CSS & JS
      –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
            integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

    <!-- Password Strength Meter JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript" src="{% static "js/password.min.js" %}"></script>

    <!-- Summernote JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript" src="{% static "js/bs-4/summernote-bs4.min.js" %}"></script>

    <!-- jquery cropper
        –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript" src="{% static "js/cropper.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery-cropper.min.js" %}"></script>


    <!-- Global CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}">

    <!-- Template specific  CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    {% block css %}{% endblock %}

    <!-- Custom css
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/account.css" %}">

    <!-- Favicon
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">

</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        <li><a href="#">About</a></li>
                        <li><a href="#">What we do</a></li>
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% provider_login_url 'github' %}">Login with Github</a></li>
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign
                                In</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:profile' %}">View Profile</a></li>
                            <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
{#                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>#}
                             <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>
<div class="container bounds circle--page">
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li{% if message.tags %}
                    class="no-bullets alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
{% block javascript %}{% endblock %}
</body>
</html>